### ISSUE TITLE
Does not seems to works when there is dots in the key

### ISSUE THREAD

**Issue by kaeh** [RockyCott/i18n-peek#1]
Seems like dots breaks the hover preview.

For example, i used this json in my en-US.json located in a custom local folder which i set in the exentions (followed the steps in the README)

```json
{
  "MODULES.MESSAGES.BUTTONS.ACCEPT": "Accept",
  "MODULES_MESSAGES_BUTTONS_ACCEPT": "Accept"
}
```

Now the hover does not find the first key but find the second
![image](https://github.com/RockyCott/i18n-peek/assets/11922723/073c6fbf-1e24-47ab-9399-1043b2260a7f)
![image](https://github.com/RockyCott/i18n-peek/assets/11922723/9af87a0e-cd82-4841-8240-7b59308091d7)

**Comment by RockyCott** [comment]
Hi,

Thank you for pointing out this issue and for the suggestion! When designing the extension, initially, it assumed that dots in keys indicated a hierarchical structure in the JSON. However, I understand that in your case, dots are used in keys without representing hierarchies.

I've updated the extension to support both approaches(v0.0.4): it now checks for an exact key match before treating dots as path separators. I would appreciate it if you could confirm whether this solution works well for you.

Additionally, I would recommend structuring JSON files hierarchically for better organization, like in the following example:

```json
{
  "MODULES": {
    "MESSAGES": {
      "BUTTONS": {
        "ACCEPT": "Accept",
        "ACCEPTED": "Accepted",
        "ACCEPTING": "Accepting",
        "ACCEPTS": "Accepts"
      }
    }
  },
  "MODULES_MESSAGES_BUTTONS_ACCEPT": "Accept"
}
```
This structure avoids key repetition and makes the file easier to maintain. Again, thank you for your feedback!

**Comment by kaeh** [comment]
Wow that was pretty quick, thanks ! :) 

It's working flawlessly.

Honestly I would prefer to work with structured json instead of what I have now (only strings with dots) but the team I works with has done it that what for a reason they gave me a year ago and I don't remember why exactly lol.

Anyway thanks for the update, love the extension :)

**Comment by RockyCott** [comment]
I'm glad to hear that the update resolved the issue and that you're enjoying the extension! :)

Thank you again for your support!
